// The workflow build's runMain boundary. Gauntlet also ships as a Claude Code
// workflow (.claude/workflows/gauntlet.js): the same five-stage pipeline,
// driven by workflow subagents. Lenses and stage prompts stay pure content
// (ADR 0004), so the workflow never carries its own copy of them by hand —
// this script embeds the shipped catalog verbatim into the hand-written
// orchestration in workflow/gauntlet.body.js (at its @@CONTENT@@ marker,
// after the meta literal) and writes the result.
//
//   bun scripts/build-workflow.ts          # regenerate
//   bun scripts/build-workflow.ts --check  # exit 1 when the committed file is stale
import * as NodeRuntime from "@effect/platform-node/NodeRuntime"
import * as NodeServices from "@effect/platform-node/NodeServices"
import * as Array from "effect/Array"
import * as Console from "effect/Console"
import * as Data from "effect/Data"
import * as Effect from "effect/Effect"
import * as FileSystem from "effect/FileSystem"
import * as Order from "effect/Order"
import * as Schema from "effect/Schema"
import { INITIAL_DEFAULT_LENSES } from "../src/cli/config.ts"
import { loadLens } from "../src/content/lens.ts"

class WorkflowStale extends Data.TaggedError("WorkflowStale")<{
  readonly path: string
}> {}

const repoRoot = `${import.meta.dirname}/..`
process.chdir(repoRoot)

const OUTPUT = ".claude/workflows/gauntlet.js"
const BODY = "workflow/gauntlet.body.js"
const PROMPTS = "content/prompts"
const LENSES = "content/lenses"
const JUDGE = "src/stages/judgment/judge.md"
const MARKER = "// @@CONTENT@@"

const jsonLiteral = Schema.encodeEffect(Schema.fromJsonString(Schema.Unknown))

const program = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem
  const check = process.argv.includes("--check")

  const promptNames = Array.sort(
    (yield* fs.readDirectory(PROMPTS)).filter((entry) => entry.endsWith(".md")),
    Order.String,
  )
  const prompts: Record<string, string> = {}
  for (const file of promptNames) {
    prompts[file.slice(0, -".md".length)] = yield* fs.readFileString(`${PROMPTS}/${file}`)
  }
  prompts["judge"] = yield* fs.readFileString(JUDGE)

  const lensNames = Array.sort(
    (yield* fs.readDirectory(LENSES))
      .filter((entry) => entry.endsWith(".md"))
      .map((entry) => entry.slice(0, -".md".length)),
    Order.String,
  )
  const lenses: Record<string, { promptText: string; finderClass: string }> = {}
  for (const name of lensNames) {
    const lens = yield* loadLens(LENSES, name)
    lenses[name] = { promptText: lens.promptText, finderClass: lens.finderClass }
  }

  // The body opens with the workflow's meta literal and a marker line; the
  // embedded content replaces the marker so meta stays the first statement.
  const body = yield* fs.readFileString(BODY)
  const content = yield* jsonLiteral({
    prompts,
    lenses,
    defaultLenses: INITIAL_DEFAULT_LENSES,
  })
  if (!body.includes(MARKER)) {
    return yield* new WorkflowStale({ path: `${BODY} (missing ${MARKER})` })
  }
  const output = body.replace(
    MARKER,
    [
      "// GENERATED by scripts/build-workflow.ts — edit workflow/gauntlet.body.js or",
      "// the content files, then rerun `bun scripts/build-workflow.ts`.",
      `const CONTENT = ${content}`,
    ].join("\n"),
  )

  if (check) {
    const current = yield* fs.readFileString(OUTPUT).pipe(
      Effect.orElseSucceed(() => ""),
    )
    if (current !== output) {
      return yield* new WorkflowStale({ path: OUTPUT })
    }
    yield* Console.log(`${OUTPUT} is up to date`)
    return
  }

  yield* fs.makeDirectory(".claude/workflows", { recursive: true })
  yield* fs.writeFileString(OUTPUT, output)
  yield* Console.log(
    `wrote ${OUTPUT} (${String(lensNames.length)} lenses, ${String(Object.keys(prompts).length)} prompts)`,
  )
})

NodeRuntime.runMain(program.pipe(Effect.provide(NodeServices.layer)))
